language: R
cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - export LC_ALL="C"
  - Rscript -e 'covr::coveralls(line_exclusions = c("R/deprecated.R", list.files("src/corpus", recursive = TRUE, full.names = TRUE)))'
