language: R
cache: packages

# valgrind (disabled; takes too long, and errors don't affect the build)
#
# r_check_args: '--use-valgrind'
#
# addons:
#  apt:
#    packages:
#    - valgrind

r:
- 3.1
- 3.2
- oldrel
- release
- devel

r_github_packages:
  - jimhester/covr

before_install:
  - make NEWS
  - make README

after_success:
  - export LC_ALL="C"
  - export TEST_WEB_RESOURCES="true"
  - Rscript -e 'covr::codecov(line_exclusions = c("R/deprecated.R", "R/wordlist.R", "src/wordlist.c", list.files("src/corpus", recursive = TRUE, full.names = TRUE)))'
